// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_05434230e22f555459cd21106aeb67e2_f5b646da_f62d_4e73_a854_ea0cba2ad6ce : PositionBinding
	{
		public override string CoherenceComponentName => "WorldPosition";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
			set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldPosition)coherenceComponent).value;
			if (!coherenceSync.HasParentWithCoherenceSync)
            {
                value += floatingOriginDelta;
            }
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (WorldPosition)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.value = Value;
			}
			else 
			{
				update.value = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldPosition();
		}
	}

	public class Binding_05434230e22f555459cd21106aeb67e2_348b87f6_0b12_4b9c_a4e2_33c6c56f19a0 : DeepPositionBinding
	{
		private global::UnityEngine.Transform CastedUnityComponent;

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_1253990227028822518";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get { return (UnityEngine.Vector3)(CastedUnityComponent.localPosition); }
			set { CastedUnityComponent.localPosition = (UnityEngine.Vector3)(value); }
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_1253990227028822518)coherenceComponent).position;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_1253990227028822518)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.position = Value;
			}
			else 
			{
				update.position = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_1253990227028822518();
		}
	}

	public class Binding_05434230e22f555459cd21106aeb67e2_82d28c7d_b15e_4d8d_959c_e3b405509e8c : DeepRotationBinding
	{
		private global::UnityEngine.Transform CastedUnityComponent;

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_1253990227028822518";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override Quaternion Value
		{
			get { return (UnityEngine.Quaternion)(CastedUnityComponent.localRotation); }
			set { CastedUnityComponent.localRotation = (UnityEngine.Quaternion)(value); }
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_1253990227028822518)coherenceComponent).rotation;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_1253990227028822518)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.rotation = Value;
			}
			else 
			{
				update.rotation = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_1253990227028822518();
		}
	}

	public class Binding_05434230e22f555459cd21106aeb67e2_150636a8_fec8_4874_9a47_bc58ad2c310f : DeepRotationBinding
	{
		private global::UnityEngine.Transform CastedUnityComponent;

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_7463586618220030189";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Quaternion Value
		{
			get { return (UnityEngine.Quaternion)(CastedUnityComponent.localRotation); }
			set { CastedUnityComponent.localRotation = (UnityEngine.Quaternion)(value); }
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_7463586618220030189)coherenceComponent).rotation;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_7463586618220030189)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.rotation = Value;
			}
			else 
			{
				update.rotation = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_7463586618220030189();
		}
	}

	public class Binding_05434230e22f555459cd21106aeb67e2_3ec3ff3e_15ff_4d10_973e_4a7fbcb0f6d7 : DeepPositionBinding
	{
		private global::UnityEngine.Transform CastedUnityComponent;

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_7463586618220030189";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override Vector3 Value
		{
			get { return (UnityEngine.Vector3)(CastedUnityComponent.localPosition); }
			set { CastedUnityComponent.localPosition = (UnityEngine.Vector3)(value); }
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_7463586618220030189)coherenceComponent).position;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_7463586618220030189)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.position = Value;
			}
			else 
			{
				update.position = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_7463586618220030189();
		}
	}


	[Preserve]
	public class CoherenceSyncTurretEnemy_05434230e22f555459cd21106aeb67e2 : CoherenceSyncBaked
	{
		private SerializeEntityID entityId;
		private Logger logger = Log.GetLogger<CoherenceSyncTurretEnemy_05434230e22f555459cd21106aeb67e2>();

		// Cached targets for commands		
		private global::EnemyHealth TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_c7beaedc_8ac9_4337_b0ed_b0cb9ad58c11_CommandTarget;		
		private global::EnemySyncInit TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_0fdf290c_9c68_42c4_b1fa_8ba86e34a1ba_CommandTarget;

		private IClient client;
		private CoherenceBridge bridge;

		private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
		{
			["f5b646da-f62d-4e73-a854-ea0cba2ad6ce"] = new Binding_05434230e22f555459cd21106aeb67e2_f5b646da_f62d_4e73_a854_ea0cba2ad6ce(),
			["348b87f6-0b12-4b9c-a4e2-33c6c56f19a0"] = new Binding_05434230e22f555459cd21106aeb67e2_348b87f6_0b12_4b9c_a4e2_33c6c56f19a0(),
			["82d28c7d-b15e-4d8d-959c-e3b405509e8c"] = new Binding_05434230e22f555459cd21106aeb67e2_82d28c7d_b15e_4d8d_959c_e3b405509e8c(),
			["150636a8-fec8-4874-9a47-bc58ad2c310f"] = new Binding_05434230e22f555459cd21106aeb67e2_150636a8_fec8_4874_9a47_bc58ad2c310f(),
			["3ec3ff3e-15ff-4d10-973e-4a7fbcb0f6d7"] = new Binding_05434230e22f555459cd21106aeb67e2_3ec3ff3e_15ff_4d10_973e_4a7fbcb0f6d7(),
		};

		private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings =
			new Dictionary<string, Action<CommandBinding, CommandsHandler>>();

		public CoherenceSyncTurretEnemy_05434230e22f555459cd21106aeb67e2()
		{
			bakedCommandBindings.Add("c7beaedc-8ac9-4337-b0ed-b0cb9ad58c11", BakeCommandBinding_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_c7beaedc_8ac9_4337_b0ed_b0cb9ad58c11);
			bakedCommandBindings.Add("0fdf290c-9c68-42c4-b1fa-8ba86e34a1ba", BakeCommandBinding_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_0fdf290c_9c68_42c4_b1fa_8ba86e34a1ba);
		}

		public override Binding BakeValueBinding(Binding valueBinding)
		{
			if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
			{
				valueBinding.CloneTo(bakedBinding);
				return bakedBinding;
			}

			return null;
		}

		public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
			{
				commandBindingBaker.Invoke(commandBinding, commandsHandler);
			}
		}
		private void BakeCommandBinding_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_c7beaedc_8ac9_4337_b0ed_b0cb9ad58c11(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_c7beaedc_8ac9_4337_b0ed_b0cb9ad58c11_CommandTarget = (global::EnemyHealth)commandBinding.UnityComponent;
			commandsHandler.AddBakedCommand("EnemyHealth.Die", "()",
				SendCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_c7beaedc_8ac9_4337_b0ed_b0cb9ad58c11, ReceiveLocalCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_c7beaedc_8ac9_4337_b0ed_b0cb9ad58c11, MessageTarget.All, TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_c7beaedc_8ac9_4337_b0ed_b0cb9ad58c11_CommandTarget,false);
		}
		private void BakeCommandBinding_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_0fdf290c_9c68_42c4_b1fa_8ba86e34a1ba(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_0fdf290c_9c68_42c4_b1fa_8ba86e34a1ba_CommandTarget = (global::EnemySyncInit)commandBinding.UnityComponent;
			commandsHandler.AddBakedCommand("EnemySyncInit.SetReferences", "(System.String)",
				SendCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_0fdf290c_9c68_42c4_b1fa_8ba86e34a1ba, ReceiveLocalCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_0fdf290c_9c68_42c4_b1fa_8ba86e34a1ba, MessageTarget.All, TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_0fdf290c_9c68_42c4_b1fa_8ba86e34a1ba_CommandTarget,false);
		}

		public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName)
		{
			if (!usesLodsAtRuntime)
			{
				return null;
			}

			if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
	
			logger.Warning($"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");

			return null;
		}

		public override void Dispose()
		{
		}

		public override void Initialize(SerializeEntityID entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
		{
			this.logger = logger.With<CoherenceSyncTurretEnemy_05434230e22f555459cd21106aeb67e2>();
			this.bridge = bridge;
			this.entityId = entityId;
			this.client = client;
		}
		void SendCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_c7beaedc_8ac9_4337_b0ed_b0cb9ad58c11(MessageTarget target, object[] args)
		{
			var command = new TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_c7beaedc_8ac9_4337_b0ed_b0cb9ad58c11();
			client.SendCommand(command, target, entityId);
		}

		void ReceiveLocalCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_c7beaedc_8ac9_4337_b0ed_b0cb9ad58c11(MessageTarget target, object[] args)
		{
			var command = new TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_c7beaedc_8ac9_4337_b0ed_b0cb9ad58c11();
			ReceiveCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_c7beaedc_8ac9_4337_b0ed_b0cb9ad58c11(command);
		}

		void ReceiveCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_c7beaedc_8ac9_4337_b0ed_b0cb9ad58c11(TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_c7beaedc_8ac9_4337_b0ed_b0cb9ad58c11 command)
		{
			var target = TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_c7beaedc_8ac9_4337_b0ed_b0cb9ad58c11_CommandTarget;
			target.Die();
		}
		void SendCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_0fdf290c_9c68_42c4_b1fa_8ba86e34a1ba(MessageTarget target, object[] args)
		{
			var command = new TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_0fdf290c_9c68_42c4_b1fa_8ba86e34a1ba();
			int i = 0;
			command.enemySpawner = (string)((System.String)args[i++]);
			client.SendCommand(command, target, entityId);
		}

		void ReceiveLocalCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_0fdf290c_9c68_42c4_b1fa_8ba86e34a1ba(MessageTarget target, object[] args)
		{
			var command = new TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_0fdf290c_9c68_42c4_b1fa_8ba86e34a1ba();
			int i = 0;
			command.enemySpawner = (string)((System.String)args[i++]);
			ReceiveCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_0fdf290c_9c68_42c4_b1fa_8ba86e34a1ba(command);
		}

		void ReceiveCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_0fdf290c_9c68_42c4_b1fa_8ba86e34a1ba(TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_0fdf290c_9c68_42c4_b1fa_8ba86e34a1ba command)
		{
			var target = TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_0fdf290c_9c68_42c4_b1fa_8ba86e34a1ba_CommandTarget;
			target.SetReferences((System.String)(command.enemySpawner));
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				case TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_c7beaedc_8ac9_4337_b0ed_b0cb9ad58c11 castedCommand:
					ReceiveCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_c7beaedc_8ac9_4337_b0ed_b0cb9ad58c11(castedCommand);
					break;
				case TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_0fdf290c_9c68_42c4_b1fa_8ba86e34a1ba castedCommand:
					ReceiveCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_0fdf290c_9c68_42c4_b1fa_8ba86e34a1ba(castedCommand);
					break;
				default:
					logger.Warning($"[CoherenceSyncTurretEnemy_05434230e22f555459cd21106aeb67e2] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
