// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_fb33efce218f91746a8e1743d2d6c0f9_9d292d24_b936_4f01_b453_e122a575981f : PositionBinding
	{
		public override string CoherenceComponentName => "WorldPosition";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
			set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldPosition)coherenceComponent).value;
			if (!coherenceSync.HasParentWithCoherenceSync)
            {
                value += floatingOriginDelta;
            }
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (WorldPosition)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.value = Value;
			}
			else 
			{
				update.value = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldPosition();
		}
	}

	public class Binding_fb33efce218f91746a8e1743d2d6c0f9_b1425544_fcbc_493e_80c6_a6af2bce2b71 : RotationBinding
	{
		public override string CoherenceComponentName => "WorldOrientation";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Quaternion Value
		{
			get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
			set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldOrientation)coherenceComponent).value;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (WorldOrientation)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.value = Value;
			}
			else 
			{
				update.value = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldOrientation();
		}
	}

	public class Binding_fb33efce218f91746a8e1743d2d6c0f9_ca2f1a12_02d3_4ab5_a994_fe0a3f3299d9 : IntBinding
	{
		private global::EnemyHealth CastedUnityComponent;

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (global::EnemyHealth)UnityComponent;
		}
		public override string CoherenceComponentName => "EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemyHealth_6193124714125256054";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override int Value
		{
			get { return (System.Int32)(CastedUnityComponent.health); }
			set { CastedUnityComponent.health = (System.Int32)(value); }
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemyHealth_6193124714125256054)coherenceComponent).health;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemyHealth_6193124714125256054)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.health = Value;
			}
			else 
			{
				update.health = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemyHealth_6193124714125256054();
		}
	}


	[Preserve]
	public class CoherenceSyncEnemyA_fb33efce218f91746a8e1743d2d6c0f9 : CoherenceSyncBaked
	{
		private SerializeEntityID entityId;
		private Logger logger = Log.GetLogger<CoherenceSyncEnemyA_fb33efce218f91746a8e1743d2d6c0f9>();

		// Cached targets for commands		
		private global::EnemyHealth EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemyHealth__char_46_Die_1930dcc7_1125_46cb_a72b_7758cbb77ce7_CommandTarget;		
		private global::EnemySyncInit EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemySyncInit__char_46_SetReferences_5e717b57_f773_4c0b_8535_2b6f27c37857_CommandTarget;

		private IClient client;
		private CoherenceBridge bridge;

		private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
		{
			["9d292d24-b936-4f01-b453-e122a575981f"] = new Binding_fb33efce218f91746a8e1743d2d6c0f9_9d292d24_b936_4f01_b453_e122a575981f(),
			["b1425544-fcbc-493e-80c6-a6af2bce2b71"] = new Binding_fb33efce218f91746a8e1743d2d6c0f9_b1425544_fcbc_493e_80c6_a6af2bce2b71(),
			["ca2f1a12-02d3-4ab5-a994-fe0a3f3299d9"] = new Binding_fb33efce218f91746a8e1743d2d6c0f9_ca2f1a12_02d3_4ab5_a994_fe0a3f3299d9(),
		};

		private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings =
			new Dictionary<string, Action<CommandBinding, CommandsHandler>>();

		public CoherenceSyncEnemyA_fb33efce218f91746a8e1743d2d6c0f9()
		{
			bakedCommandBindings.Add("1930dcc7-1125-46cb-a72b-7758cbb77ce7", BakeCommandBinding_EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemyHealth__char_46_Die_1930dcc7_1125_46cb_a72b_7758cbb77ce7);
			bakedCommandBindings.Add("5e717b57-f773-4c0b-8535-2b6f27c37857", BakeCommandBinding_EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemySyncInit__char_46_SetReferences_5e717b57_f773_4c0b_8535_2b6f27c37857);
		}

		public override Binding BakeValueBinding(Binding valueBinding)
		{
			if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
			{
				valueBinding.CloneTo(bakedBinding);
				return bakedBinding;
			}

			return null;
		}

		public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
			{
				commandBindingBaker.Invoke(commandBinding, commandsHandler);
			}
		}
		private void BakeCommandBinding_EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemyHealth__char_46_Die_1930dcc7_1125_46cb_a72b_7758cbb77ce7(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemyHealth__char_46_Die_1930dcc7_1125_46cb_a72b_7758cbb77ce7_CommandTarget = (global::EnemyHealth)commandBinding.UnityComponent;
			commandsHandler.AddBakedCommand("EnemyHealth.Die", "()",
				SendCommand_EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemyHealth__char_46_Die_1930dcc7_1125_46cb_a72b_7758cbb77ce7, ReceiveLocalCommand_EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemyHealth__char_46_Die_1930dcc7_1125_46cb_a72b_7758cbb77ce7, MessageTarget.All, EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemyHealth__char_46_Die_1930dcc7_1125_46cb_a72b_7758cbb77ce7_CommandTarget,false);
		}
		private void BakeCommandBinding_EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemySyncInit__char_46_SetReferences_5e717b57_f773_4c0b_8535_2b6f27c37857(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemySyncInit__char_46_SetReferences_5e717b57_f773_4c0b_8535_2b6f27c37857_CommandTarget = (global::EnemySyncInit)commandBinding.UnityComponent;
			commandsHandler.AddBakedCommand("EnemySyncInit.SetReferences", "(System.String)",
				SendCommand_EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemySyncInit__char_46_SetReferences_5e717b57_f773_4c0b_8535_2b6f27c37857, ReceiveLocalCommand_EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemySyncInit__char_46_SetReferences_5e717b57_f773_4c0b_8535_2b6f27c37857, MessageTarget.All, EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemySyncInit__char_46_SetReferences_5e717b57_f773_4c0b_8535_2b6f27c37857_CommandTarget,false);
		}

		public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName)
		{
			if (!usesLodsAtRuntime)
			{
				return null;
			}

			if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
	
			logger.Warning($"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");

			return null;
		}

		public override void Dispose()
		{
		}

		public override void Initialize(SerializeEntityID entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
		{
			this.logger = logger.With<CoherenceSyncEnemyA_fb33efce218f91746a8e1743d2d6c0f9>();
			this.bridge = bridge;
			this.entityId = entityId;
			this.client = client;
		}
		void SendCommand_EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemyHealth__char_46_Die_1930dcc7_1125_46cb_a72b_7758cbb77ce7(MessageTarget target, object[] args)
		{
			var command = new EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemyHealth__char_46_Die_1930dcc7_1125_46cb_a72b_7758cbb77ce7();
			client.SendCommand(command, target, entityId);
		}

		void ReceiveLocalCommand_EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemyHealth__char_46_Die_1930dcc7_1125_46cb_a72b_7758cbb77ce7(MessageTarget target, object[] args)
		{
			var command = new EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemyHealth__char_46_Die_1930dcc7_1125_46cb_a72b_7758cbb77ce7();
			ReceiveCommand_EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemyHealth__char_46_Die_1930dcc7_1125_46cb_a72b_7758cbb77ce7(command);
		}

		void ReceiveCommand_EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemyHealth__char_46_Die_1930dcc7_1125_46cb_a72b_7758cbb77ce7(EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemyHealth__char_46_Die_1930dcc7_1125_46cb_a72b_7758cbb77ce7 command)
		{
			var target = EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemyHealth__char_46_Die_1930dcc7_1125_46cb_a72b_7758cbb77ce7_CommandTarget;
			target.Die();
		}
		void SendCommand_EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemySyncInit__char_46_SetReferences_5e717b57_f773_4c0b_8535_2b6f27c37857(MessageTarget target, object[] args)
		{
			var command = new EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemySyncInit__char_46_SetReferences_5e717b57_f773_4c0b_8535_2b6f27c37857();
			int i = 0;
			command.enemySpawner = (string)((System.String)args[i++]);
			client.SendCommand(command, target, entityId);
		}

		void ReceiveLocalCommand_EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemySyncInit__char_46_SetReferences_5e717b57_f773_4c0b_8535_2b6f27c37857(MessageTarget target, object[] args)
		{
			var command = new EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemySyncInit__char_46_SetReferences_5e717b57_f773_4c0b_8535_2b6f27c37857();
			int i = 0;
			command.enemySpawner = (string)((System.String)args[i++]);
			ReceiveCommand_EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemySyncInit__char_46_SetReferences_5e717b57_f773_4c0b_8535_2b6f27c37857(command);
		}

		void ReceiveCommand_EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemySyncInit__char_46_SetReferences_5e717b57_f773_4c0b_8535_2b6f27c37857(EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemySyncInit__char_46_SetReferences_5e717b57_f773_4c0b_8535_2b6f27c37857 command)
		{
			var target = EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemySyncInit__char_46_SetReferences_5e717b57_f773_4c0b_8535_2b6f27c37857_CommandTarget;
			target.SetReferences((System.String)(command.enemySpawner));
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				case EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemyHealth__char_46_Die_1930dcc7_1125_46cb_a72b_7758cbb77ce7 castedCommand:
					ReceiveCommand_EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemyHealth__char_46_Die_1930dcc7_1125_46cb_a72b_7758cbb77ce7(castedCommand);
					break;
				case EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemySyncInit__char_46_SetReferences_5e717b57_f773_4c0b_8535_2b6f27c37857 castedCommand:
					ReceiveCommand_EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemySyncInit__char_46_SetReferences_5e717b57_f773_4c0b_8535_2b6f27c37857(castedCommand);
					break;
				default:
					logger.Warning($"[CoherenceSyncEnemyA_fb33efce218f91746a8e1743d2d6c0f9] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
