// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_7365a46dbef03be41b6173e6147d68d1_d00dc6a7_44ee_487d_b691_89f762032836 : PositionBinding
	{
		public override string CoherenceComponentName => "WorldPosition";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
			set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldPosition)coherenceComponent).value;
			if (!coherenceSync.HasParentWithCoherenceSync)
            {
                value += floatingOriginDelta;
            }
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (WorldPosition)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.value = Value;
			}
			else 
			{
				update.value = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldPosition();
		}
	}

	public class Binding_7365a46dbef03be41b6173e6147d68d1_605d18af_fc8f_4b71_9351_7191d77d484e : RotationBinding
	{
		public override string CoherenceComponentName => "WorldOrientation";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Quaternion Value
		{
			get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
			set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldOrientation)coherenceComponent).value;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (WorldOrientation)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.value = Value;
			}
			else 
			{
				update.value = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldOrientation();
		}
	}


	[Preserve]
	public class CoherenceSyncEnemy_7365a46dbef03be41b6173e6147d68d1 : CoherenceSyncBaked
	{
		private SerializeEntityID entityId;
		private Logger logger = Log.GetLogger<CoherenceSyncEnemy_7365a46dbef03be41b6173e6147d68d1>();

		// Cached targets for commands		
		private global::EnemyHealth Enemy_7365a46dbef03be41b6173e6147d68d1_EnemyHealth__char_46_Die_3a86c700_23a2_4566_a6c0_96acf7d95428_CommandTarget;		
		private global::EnemySyncInit Enemy_7365a46dbef03be41b6173e6147d68d1_EnemySyncInit__char_46_SetReferences_b98d46b8_119e_4f49_9104_d0bbf89a99de_CommandTarget;

		private IClient client;
		private CoherenceBridge bridge;

		private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
		{
			["d00dc6a7-44ee-487d-b691-89f762032836"] = new Binding_7365a46dbef03be41b6173e6147d68d1_d00dc6a7_44ee_487d_b691_89f762032836(),
			["605d18af-fc8f-4b71-9351-7191d77d484e"] = new Binding_7365a46dbef03be41b6173e6147d68d1_605d18af_fc8f_4b71_9351_7191d77d484e(),
		};

		private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings =
			new Dictionary<string, Action<CommandBinding, CommandsHandler>>();

		public CoherenceSyncEnemy_7365a46dbef03be41b6173e6147d68d1()
		{
			bakedCommandBindings.Add("3a86c700-23a2-4566-a6c0-96acf7d95428", BakeCommandBinding_Enemy_7365a46dbef03be41b6173e6147d68d1_EnemyHealth__char_46_Die_3a86c700_23a2_4566_a6c0_96acf7d95428);
			bakedCommandBindings.Add("b98d46b8-119e-4f49-9104-d0bbf89a99de", BakeCommandBinding_Enemy_7365a46dbef03be41b6173e6147d68d1_EnemySyncInit__char_46_SetReferences_b98d46b8_119e_4f49_9104_d0bbf89a99de);
		}

		public override Binding BakeValueBinding(Binding valueBinding)
		{
			if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
			{
				valueBinding.CloneTo(bakedBinding);
				return bakedBinding;
			}

			return null;
		}

		public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
			{
				commandBindingBaker.Invoke(commandBinding, commandsHandler);
			}
		}
		private void BakeCommandBinding_Enemy_7365a46dbef03be41b6173e6147d68d1_EnemyHealth__char_46_Die_3a86c700_23a2_4566_a6c0_96acf7d95428(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			Enemy_7365a46dbef03be41b6173e6147d68d1_EnemyHealth__char_46_Die_3a86c700_23a2_4566_a6c0_96acf7d95428_CommandTarget = (global::EnemyHealth)commandBinding.UnityComponent;
			commandsHandler.AddBakedCommand("EnemyHealth.Die", "()",
				SendCommand_Enemy_7365a46dbef03be41b6173e6147d68d1_EnemyHealth__char_46_Die_3a86c700_23a2_4566_a6c0_96acf7d95428, ReceiveLocalCommand_Enemy_7365a46dbef03be41b6173e6147d68d1_EnemyHealth__char_46_Die_3a86c700_23a2_4566_a6c0_96acf7d95428, MessageTarget.All, Enemy_7365a46dbef03be41b6173e6147d68d1_EnemyHealth__char_46_Die_3a86c700_23a2_4566_a6c0_96acf7d95428_CommandTarget,false);
		}
		private void BakeCommandBinding_Enemy_7365a46dbef03be41b6173e6147d68d1_EnemySyncInit__char_46_SetReferences_b98d46b8_119e_4f49_9104_d0bbf89a99de(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			Enemy_7365a46dbef03be41b6173e6147d68d1_EnemySyncInit__char_46_SetReferences_b98d46b8_119e_4f49_9104_d0bbf89a99de_CommandTarget = (global::EnemySyncInit)commandBinding.UnityComponent;
			commandsHandler.AddBakedCommand("EnemySyncInit.SetReferences", "(System.String)",
				SendCommand_Enemy_7365a46dbef03be41b6173e6147d68d1_EnemySyncInit__char_46_SetReferences_b98d46b8_119e_4f49_9104_d0bbf89a99de, ReceiveLocalCommand_Enemy_7365a46dbef03be41b6173e6147d68d1_EnemySyncInit__char_46_SetReferences_b98d46b8_119e_4f49_9104_d0bbf89a99de, MessageTarget.All, Enemy_7365a46dbef03be41b6173e6147d68d1_EnemySyncInit__char_46_SetReferences_b98d46b8_119e_4f49_9104_d0bbf89a99de_CommandTarget,false);
		}

		public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName)
		{
			if (!usesLodsAtRuntime)
			{
				return null;
			}

			if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
	
			logger.Warning($"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");

			return null;
		}

		public override void Dispose()
		{
		}

		public override void Initialize(SerializeEntityID entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
		{
			this.logger = logger.With<CoherenceSyncEnemy_7365a46dbef03be41b6173e6147d68d1>();
			this.bridge = bridge;
			this.entityId = entityId;
			this.client = client;
		}
		void SendCommand_Enemy_7365a46dbef03be41b6173e6147d68d1_EnemyHealth__char_46_Die_3a86c700_23a2_4566_a6c0_96acf7d95428(MessageTarget target, object[] args)
		{
			var command = new Enemy_7365a46dbef03be41b6173e6147d68d1_EnemyHealth__char_46_Die_3a86c700_23a2_4566_a6c0_96acf7d95428();
			client.SendCommand(command, target, entityId);
		}

		void ReceiveLocalCommand_Enemy_7365a46dbef03be41b6173e6147d68d1_EnemyHealth__char_46_Die_3a86c700_23a2_4566_a6c0_96acf7d95428(MessageTarget target, object[] args)
		{
			var command = new Enemy_7365a46dbef03be41b6173e6147d68d1_EnemyHealth__char_46_Die_3a86c700_23a2_4566_a6c0_96acf7d95428();
			ReceiveCommand_Enemy_7365a46dbef03be41b6173e6147d68d1_EnemyHealth__char_46_Die_3a86c700_23a2_4566_a6c0_96acf7d95428(command);
		}

		void ReceiveCommand_Enemy_7365a46dbef03be41b6173e6147d68d1_EnemyHealth__char_46_Die_3a86c700_23a2_4566_a6c0_96acf7d95428(Enemy_7365a46dbef03be41b6173e6147d68d1_EnemyHealth__char_46_Die_3a86c700_23a2_4566_a6c0_96acf7d95428 command)
		{
			var target = Enemy_7365a46dbef03be41b6173e6147d68d1_EnemyHealth__char_46_Die_3a86c700_23a2_4566_a6c0_96acf7d95428_CommandTarget;
			target.Die();
		}
		void SendCommand_Enemy_7365a46dbef03be41b6173e6147d68d1_EnemySyncInit__char_46_SetReferences_b98d46b8_119e_4f49_9104_d0bbf89a99de(MessageTarget target, object[] args)
		{
			var command = new Enemy_7365a46dbef03be41b6173e6147d68d1_EnemySyncInit__char_46_SetReferences_b98d46b8_119e_4f49_9104_d0bbf89a99de();
			int i = 0;
			command.enemySpawner = (string)((System.String)args[i++]);
			client.SendCommand(command, target, entityId);
		}

		void ReceiveLocalCommand_Enemy_7365a46dbef03be41b6173e6147d68d1_EnemySyncInit__char_46_SetReferences_b98d46b8_119e_4f49_9104_d0bbf89a99de(MessageTarget target, object[] args)
		{
			var command = new Enemy_7365a46dbef03be41b6173e6147d68d1_EnemySyncInit__char_46_SetReferences_b98d46b8_119e_4f49_9104_d0bbf89a99de();
			int i = 0;
			command.enemySpawner = (string)((System.String)args[i++]);
			ReceiveCommand_Enemy_7365a46dbef03be41b6173e6147d68d1_EnemySyncInit__char_46_SetReferences_b98d46b8_119e_4f49_9104_d0bbf89a99de(command);
		}

		void ReceiveCommand_Enemy_7365a46dbef03be41b6173e6147d68d1_EnemySyncInit__char_46_SetReferences_b98d46b8_119e_4f49_9104_d0bbf89a99de(Enemy_7365a46dbef03be41b6173e6147d68d1_EnemySyncInit__char_46_SetReferences_b98d46b8_119e_4f49_9104_d0bbf89a99de command)
		{
			var target = Enemy_7365a46dbef03be41b6173e6147d68d1_EnemySyncInit__char_46_SetReferences_b98d46b8_119e_4f49_9104_d0bbf89a99de_CommandTarget;
			target.SetReferences((System.String)(command.enemySpawner));
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				case Enemy_7365a46dbef03be41b6173e6147d68d1_EnemyHealth__char_46_Die_3a86c700_23a2_4566_a6c0_96acf7d95428 castedCommand:
					ReceiveCommand_Enemy_7365a46dbef03be41b6173e6147d68d1_EnemyHealth__char_46_Die_3a86c700_23a2_4566_a6c0_96acf7d95428(castedCommand);
					break;
				case Enemy_7365a46dbef03be41b6173e6147d68d1_EnemySyncInit__char_46_SetReferences_b98d46b8_119e_4f49_9104_d0bbf89a99de castedCommand:
					ReceiveCommand_Enemy_7365a46dbef03be41b6173e6147d68d1_EnemySyncInit__char_46_SetReferences_b98d46b8_119e_4f49_9104_d0bbf89a99de(castedCommand);
					break;
				default:
					logger.Warning($"[CoherenceSyncEnemy_7365a46dbef03be41b6173e6147d68d1] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
