// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_5714c7c58551c2843bebf23f9feebbe2_29c52beb_2f88_4a5c_8671_bdd3c7381413 : PositionBinding
	{
		public override string CoherenceComponentName => "WorldPosition";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
			set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldPosition)coherenceComponent).value;
			if (!coherenceSync.HasParentWithCoherenceSync)
            {
                value += floatingOriginDelta;
            }
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (WorldPosition)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.value = Value;
			}
			else 
			{
				update.value = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldPosition();
		}
	}

	public class Binding_5714c7c58551c2843bebf23f9feebbe2_ae41d8a9_d397_4dcf_aef7_7d750cab39e6 : RotationBinding
	{
		public override string CoherenceComponentName => "WorldOrientation";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Quaternion Value
		{
			get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
			set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldOrientation)coherenceComponent).value;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (WorldOrientation)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.value = Value;
			}
			else 
			{
				update.value = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldOrientation();
		}
	}

	public class Binding_5714c7c58551c2843bebf23f9feebbe2_f15477a6_902d_491c_8502_ba280fd71556 : IntBinding
	{
		private global::EnemyHealth CastedUnityComponent;

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (global::EnemyHealth)UnityComponent;
		}
		public override string CoherenceComponentName => "EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth_6193124714125256054";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override int Value
		{
			get { return (System.Int32)(CastedUnityComponent.health); }
			set { CastedUnityComponent.health = (System.Int32)(value); }
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth_6193124714125256054)coherenceComponent).health;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth_6193124714125256054)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.health = Value;
			}
			else 
			{
				update.health = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth_6193124714125256054();
		}
	}


	[Preserve]
	public class CoherenceSyncEnemyB_5714c7c58551c2843bebf23f9feebbe2 : CoherenceSyncBaked
	{
		private SerializeEntityID entityId;
		private Logger logger = Log.GetLogger<CoherenceSyncEnemyB_5714c7c58551c2843bebf23f9feebbe2>();

		// Cached targets for commands		
		private global::EnemyHealth EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_7d5aa261_3832_45b3_8e0b_000a6ba68241_CommandTarget;		
		private global::EnemySyncInit EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemySyncInit__char_46_SetReferences_a36f68fc_d2ff_407e_b1bb_7a6268791147_CommandTarget;

		private IClient client;
		private CoherenceBridge bridge;

		private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
		{
			["29c52beb-2f88-4a5c-8671-bdd3c7381413"] = new Binding_5714c7c58551c2843bebf23f9feebbe2_29c52beb_2f88_4a5c_8671_bdd3c7381413(),
			["ae41d8a9-d397-4dcf-aef7-7d750cab39e6"] = new Binding_5714c7c58551c2843bebf23f9feebbe2_ae41d8a9_d397_4dcf_aef7_7d750cab39e6(),
			["f15477a6-902d-491c-8502-ba280fd71556"] = new Binding_5714c7c58551c2843bebf23f9feebbe2_f15477a6_902d_491c_8502_ba280fd71556(),
		};

		private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings =
			new Dictionary<string, Action<CommandBinding, CommandsHandler>>();

		public CoherenceSyncEnemyB_5714c7c58551c2843bebf23f9feebbe2()
		{
			bakedCommandBindings.Add("7d5aa261-3832-45b3-8e0b-000a6ba68241", BakeCommandBinding_EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_7d5aa261_3832_45b3_8e0b_000a6ba68241);
			bakedCommandBindings.Add("a36f68fc-d2ff-407e-b1bb-7a6268791147", BakeCommandBinding_EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemySyncInit__char_46_SetReferences_a36f68fc_d2ff_407e_b1bb_7a6268791147);
		}

		public override Binding BakeValueBinding(Binding valueBinding)
		{
			if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
			{
				valueBinding.CloneTo(bakedBinding);
				return bakedBinding;
			}

			return null;
		}

		public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
			{
				commandBindingBaker.Invoke(commandBinding, commandsHandler);
			}
		}
		private void BakeCommandBinding_EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_7d5aa261_3832_45b3_8e0b_000a6ba68241(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_7d5aa261_3832_45b3_8e0b_000a6ba68241_CommandTarget = (global::EnemyHealth)commandBinding.UnityComponent;
			commandsHandler.AddBakedCommand("EnemyHealth.Die", "()",
				SendCommand_EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_7d5aa261_3832_45b3_8e0b_000a6ba68241, ReceiveLocalCommand_EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_7d5aa261_3832_45b3_8e0b_000a6ba68241, MessageTarget.All, EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_7d5aa261_3832_45b3_8e0b_000a6ba68241_CommandTarget,false);
		}
		private void BakeCommandBinding_EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemySyncInit__char_46_SetReferences_a36f68fc_d2ff_407e_b1bb_7a6268791147(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemySyncInit__char_46_SetReferences_a36f68fc_d2ff_407e_b1bb_7a6268791147_CommandTarget = (global::EnemySyncInit)commandBinding.UnityComponent;
			commandsHandler.AddBakedCommand("EnemySyncInit.SetReferences", "(System.String)",
				SendCommand_EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemySyncInit__char_46_SetReferences_a36f68fc_d2ff_407e_b1bb_7a6268791147, ReceiveLocalCommand_EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemySyncInit__char_46_SetReferences_a36f68fc_d2ff_407e_b1bb_7a6268791147, MessageTarget.All, EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemySyncInit__char_46_SetReferences_a36f68fc_d2ff_407e_b1bb_7a6268791147_CommandTarget,false);
		}

		public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName)
		{
			if (!usesLodsAtRuntime)
			{
				return null;
			}

			if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
	
			logger.Warning($"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");

			return null;
		}

		public override void Dispose()
		{
		}

		public override void Initialize(SerializeEntityID entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
		{
			this.logger = logger.With<CoherenceSyncEnemyB_5714c7c58551c2843bebf23f9feebbe2>();
			this.bridge = bridge;
			this.entityId = entityId;
			this.client = client;
		}
		void SendCommand_EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_7d5aa261_3832_45b3_8e0b_000a6ba68241(MessageTarget target, object[] args)
		{
			var command = new EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_7d5aa261_3832_45b3_8e0b_000a6ba68241();
			client.SendCommand(command, target, entityId);
		}

		void ReceiveLocalCommand_EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_7d5aa261_3832_45b3_8e0b_000a6ba68241(MessageTarget target, object[] args)
		{
			var command = new EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_7d5aa261_3832_45b3_8e0b_000a6ba68241();
			ReceiveCommand_EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_7d5aa261_3832_45b3_8e0b_000a6ba68241(command);
		}

		void ReceiveCommand_EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_7d5aa261_3832_45b3_8e0b_000a6ba68241(EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_7d5aa261_3832_45b3_8e0b_000a6ba68241 command)
		{
			var target = EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_7d5aa261_3832_45b3_8e0b_000a6ba68241_CommandTarget;
			target.Die();
		}
		void SendCommand_EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemySyncInit__char_46_SetReferences_a36f68fc_d2ff_407e_b1bb_7a6268791147(MessageTarget target, object[] args)
		{
			var command = new EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemySyncInit__char_46_SetReferences_a36f68fc_d2ff_407e_b1bb_7a6268791147();
			int i = 0;
			command.enemySpawner = (string)((System.String)args[i++]);
			client.SendCommand(command, target, entityId);
		}

		void ReceiveLocalCommand_EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemySyncInit__char_46_SetReferences_a36f68fc_d2ff_407e_b1bb_7a6268791147(MessageTarget target, object[] args)
		{
			var command = new EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemySyncInit__char_46_SetReferences_a36f68fc_d2ff_407e_b1bb_7a6268791147();
			int i = 0;
			command.enemySpawner = (string)((System.String)args[i++]);
			ReceiveCommand_EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemySyncInit__char_46_SetReferences_a36f68fc_d2ff_407e_b1bb_7a6268791147(command);
		}

		void ReceiveCommand_EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemySyncInit__char_46_SetReferences_a36f68fc_d2ff_407e_b1bb_7a6268791147(EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemySyncInit__char_46_SetReferences_a36f68fc_d2ff_407e_b1bb_7a6268791147 command)
		{
			var target = EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemySyncInit__char_46_SetReferences_a36f68fc_d2ff_407e_b1bb_7a6268791147_CommandTarget;
			target.SetReferences((System.String)(command.enemySpawner));
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				case EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_7d5aa261_3832_45b3_8e0b_000a6ba68241 castedCommand:
					ReceiveCommand_EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_7d5aa261_3832_45b3_8e0b_000a6ba68241(castedCommand);
					break;
				case EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemySyncInit__char_46_SetReferences_a36f68fc_d2ff_407e_b1bb_7a6268791147 castedCommand:
					ReceiveCommand_EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemySyncInit__char_46_SetReferences_a36f68fc_d2ff_407e_b1bb_7a6268791147(castedCommand);
					break;
				default:
					logger.Warning($"[CoherenceSyncEnemyB_5714c7c58551c2843bebf23f9feebbe2] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
