// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_05434230e22f555459cd21106aeb67e2_499d7f26_6ac9_4784_bb43_f4522b37c202 : PositionBinding
	{
		public override string CoherenceComponentName => "WorldPosition";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
			set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldPosition)coherenceComponent).value;
			if (!coherenceSync.HasParentWithCoherenceSync)
            {
                value += floatingOriginDelta;
            }
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (WorldPosition)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.value = Value;
			}
			else 
			{
				update.value = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldPosition();
		}
	}

	public class Binding_05434230e22f555459cd21106aeb67e2_e63bd5f9_dbab_40b6_9dbc_30196e40402e : DeepRotationBinding
	{
		private global::UnityEngine.Transform CastedUnityComponent;

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_1253990227028822518";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Quaternion Value
		{
			get { return (UnityEngine.Quaternion)(CastedUnityComponent.localRotation); }
			set { CastedUnityComponent.localRotation = (UnityEngine.Quaternion)(value); }
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_1253990227028822518)coherenceComponent).rotation;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_1253990227028822518)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.rotation = Value;
			}
			else 
			{
				update.rotation = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_1253990227028822518();
		}
	}

	public class Binding_05434230e22f555459cd21106aeb67e2_970553cb_3397_4865_bde7_40fef63d2fe2 : DeepPositionBinding
	{
		private global::UnityEngine.Transform CastedUnityComponent;

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_1253990227028822518";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override Vector3 Value
		{
			get { return (UnityEngine.Vector3)(CastedUnityComponent.localPosition); }
			set { CastedUnityComponent.localPosition = (UnityEngine.Vector3)(value); }
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_1253990227028822518)coherenceComponent).position;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_1253990227028822518)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.position = Value;
			}
			else 
			{
				update.position = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_1253990227028822518();
		}
	}

	public class Binding_05434230e22f555459cd21106aeb67e2_09365dcb_fbf6_420c_89b1_e1b2947bd638 : DeepRotationBinding
	{
		private global::UnityEngine.Transform CastedUnityComponent;

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_7463586618220030189";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Quaternion Value
		{
			get { return (UnityEngine.Quaternion)(CastedUnityComponent.localRotation); }
			set { CastedUnityComponent.localRotation = (UnityEngine.Quaternion)(value); }
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_7463586618220030189)coherenceComponent).rotation;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_7463586618220030189)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.rotation = Value;
			}
			else 
			{
				update.rotation = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_7463586618220030189();
		}
	}

	public class Binding_05434230e22f555459cd21106aeb67e2_c7268b90_a2ac_473e_9afa_1064c02c9336 : DeepPositionBinding
	{
		private global::UnityEngine.Transform CastedUnityComponent;

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_7463586618220030189";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override Vector3 Value
		{
			get { return (UnityEngine.Vector3)(CastedUnityComponent.localPosition); }
			set { CastedUnityComponent.localPosition = (UnityEngine.Vector3)(value); }
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_7463586618220030189)coherenceComponent).position;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_7463586618220030189)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.position = Value;
			}
			else 
			{
				update.position = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new TurretEnemy_05434230e22f555459cd21106aeb67e2_UnityEngine__char_46_Transform_7463586618220030189();
		}
	}


	[Preserve]
	public class CoherenceSyncTurretEnemy_05434230e22f555459cd21106aeb67e2 : CoherenceSyncBaked
	{
		private SerializeEntityID entityId;
		private Logger logger = Log.GetLogger<CoherenceSyncTurretEnemy_05434230e22f555459cd21106aeb67e2>();

		// Cached targets for commands		
		private global::EnemyHealth TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_fa79d985_aa4b_4352_9ecf_918c5ebf41c4_CommandTarget;		
		private global::EnemySyncInit TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_70dae4b5_9b71_46d6_9e52_1ab2c3d43453_CommandTarget;

		private IClient client;
		private CoherenceBridge bridge;

		private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
		{
			["499d7f26-6ac9-4784-bb43-f4522b37c202"] = new Binding_05434230e22f555459cd21106aeb67e2_499d7f26_6ac9_4784_bb43_f4522b37c202(),
			["e63bd5f9-dbab-40b6-9dbc-30196e40402e"] = new Binding_05434230e22f555459cd21106aeb67e2_e63bd5f9_dbab_40b6_9dbc_30196e40402e(),
			["970553cb-3397-4865-bde7-40fef63d2fe2"] = new Binding_05434230e22f555459cd21106aeb67e2_970553cb_3397_4865_bde7_40fef63d2fe2(),
			["09365dcb-fbf6-420c-89b1-e1b2947bd638"] = new Binding_05434230e22f555459cd21106aeb67e2_09365dcb_fbf6_420c_89b1_e1b2947bd638(),
			["c7268b90-a2ac-473e-9afa-1064c02c9336"] = new Binding_05434230e22f555459cd21106aeb67e2_c7268b90_a2ac_473e_9afa_1064c02c9336(),
		};

		private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings =
			new Dictionary<string, Action<CommandBinding, CommandsHandler>>();

		public CoherenceSyncTurretEnemy_05434230e22f555459cd21106aeb67e2()
		{
			bakedCommandBindings.Add("fa79d985-aa4b-4352-9ecf-918c5ebf41c4", BakeCommandBinding_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_fa79d985_aa4b_4352_9ecf_918c5ebf41c4);
			bakedCommandBindings.Add("70dae4b5-9b71-46d6-9e52-1ab2c3d43453", BakeCommandBinding_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_70dae4b5_9b71_46d6_9e52_1ab2c3d43453);
		}

		public override Binding BakeValueBinding(Binding valueBinding)
		{
			if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
			{
				valueBinding.CloneTo(bakedBinding);
				return bakedBinding;
			}

			return null;
		}

		public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
			{
				commandBindingBaker.Invoke(commandBinding, commandsHandler);
			}
		}
		private void BakeCommandBinding_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_fa79d985_aa4b_4352_9ecf_918c5ebf41c4(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_fa79d985_aa4b_4352_9ecf_918c5ebf41c4_CommandTarget = (global::EnemyHealth)commandBinding.UnityComponent;
			commandsHandler.AddBakedCommand("EnemyHealth.Die", "()",
				SendCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_fa79d985_aa4b_4352_9ecf_918c5ebf41c4, ReceiveLocalCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_fa79d985_aa4b_4352_9ecf_918c5ebf41c4, MessageTarget.All, TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_fa79d985_aa4b_4352_9ecf_918c5ebf41c4_CommandTarget,false);
		}
		private void BakeCommandBinding_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_70dae4b5_9b71_46d6_9e52_1ab2c3d43453(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_70dae4b5_9b71_46d6_9e52_1ab2c3d43453_CommandTarget = (global::EnemySyncInit)commandBinding.UnityComponent;
			commandsHandler.AddBakedCommand("EnemySyncInit.SetReferences", "(System.String)",
				SendCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_70dae4b5_9b71_46d6_9e52_1ab2c3d43453, ReceiveLocalCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_70dae4b5_9b71_46d6_9e52_1ab2c3d43453, MessageTarget.All, TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_70dae4b5_9b71_46d6_9e52_1ab2c3d43453_CommandTarget,false);
		}

		public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName)
		{
			if (!usesLodsAtRuntime)
			{
				return null;
			}

			if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
	
			logger.Warning($"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");

			return null;
		}

		public override void Dispose()
		{
		}

		public override void Initialize(SerializeEntityID entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
		{
			this.logger = logger.With<CoherenceSyncTurretEnemy_05434230e22f555459cd21106aeb67e2>();
			this.bridge = bridge;
			this.entityId = entityId;
			this.client = client;
		}
		void SendCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_fa79d985_aa4b_4352_9ecf_918c5ebf41c4(MessageTarget target, object[] args)
		{
			var command = new TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_fa79d985_aa4b_4352_9ecf_918c5ebf41c4();
			client.SendCommand(command, target, entityId);
		}

		void ReceiveLocalCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_fa79d985_aa4b_4352_9ecf_918c5ebf41c4(MessageTarget target, object[] args)
		{
			var command = new TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_fa79d985_aa4b_4352_9ecf_918c5ebf41c4();
			ReceiveCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_fa79d985_aa4b_4352_9ecf_918c5ebf41c4(command);
		}

		void ReceiveCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_fa79d985_aa4b_4352_9ecf_918c5ebf41c4(TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_fa79d985_aa4b_4352_9ecf_918c5ebf41c4 command)
		{
			var target = TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_fa79d985_aa4b_4352_9ecf_918c5ebf41c4_CommandTarget;
			target.Die();
		}
		void SendCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_70dae4b5_9b71_46d6_9e52_1ab2c3d43453(MessageTarget target, object[] args)
		{
			var command = new TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_70dae4b5_9b71_46d6_9e52_1ab2c3d43453();
			int i = 0;
			command.enemySpawner = (string)((System.String)args[i++]);
			client.SendCommand(command, target, entityId);
		}

		void ReceiveLocalCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_70dae4b5_9b71_46d6_9e52_1ab2c3d43453(MessageTarget target, object[] args)
		{
			var command = new TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_70dae4b5_9b71_46d6_9e52_1ab2c3d43453();
			int i = 0;
			command.enemySpawner = (string)((System.String)args[i++]);
			ReceiveCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_70dae4b5_9b71_46d6_9e52_1ab2c3d43453(command);
		}

		void ReceiveCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_70dae4b5_9b71_46d6_9e52_1ab2c3d43453(TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_70dae4b5_9b71_46d6_9e52_1ab2c3d43453 command)
		{
			var target = TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_70dae4b5_9b71_46d6_9e52_1ab2c3d43453_CommandTarget;
			target.SetReferences((System.String)(command.enemySpawner));
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				case TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_fa79d985_aa4b_4352_9ecf_918c5ebf41c4 castedCommand:
					ReceiveCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_fa79d985_aa4b_4352_9ecf_918c5ebf41c4(castedCommand);
					break;
				case TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_70dae4b5_9b71_46d6_9e52_1ab2c3d43453 castedCommand:
					ReceiveCommand_TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemySyncInit__char_46_SetReferences_70dae4b5_9b71_46d6_9e52_1ab2c3d43453(castedCommand);
					break;
				default:
					logger.Warning($"[CoherenceSyncTurretEnemy_05434230e22f555459cd21106aeb67e2] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
