// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_75a6438d17923ed4bbf57e0d1b70a8fa_ba447dfb_1812_4d5e_b886_8215e6029ca7 : PositionBinding
	{
		public override string CoherenceComponentName => "WorldPosition";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
			set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldPosition)coherenceComponent).value;
			if (!coherenceSync.HasParentWithCoherenceSync)
            {
                value += floatingOriginDelta;
            }
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (WorldPosition)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.value = Value;
			}
			else 
			{
				update.value = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldPosition();
		}
	}

	public class Binding_75a6438d17923ed4bbf57e0d1b70a8fa_ddb74f89_d2d9_4ce0_87c5_aba73101896b : RotationBinding
	{
		public override string CoherenceComponentName => "WorldOrientation";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Quaternion Value
		{
			get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
			set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldOrientation)coherenceComponent).value;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (WorldOrientation)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.value = Value;
			}
			else 
			{
				update.value = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldOrientation();
		}
	}

	public class Binding_75a6438d17923ed4bbf57e0d1b70a8fa_84ab2c91_ef90_4d6b_be49_7f4cb30dc3a9 : IntBinding
	{
		private global::EnemyHealth CastedUnityComponent;

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (global::EnemyHealth)UnityComponent;
		}
		public override string CoherenceComponentName => "EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth_6193124714125256054";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override int Value
		{
			get { return (System.Int32)(CastedUnityComponent.health); }
			set { CastedUnityComponent.health = (System.Int32)(value); }
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth_6193124714125256054)coherenceComponent).health;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth_6193124714125256054)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.health = Value;
			}
			else 
			{
				update.health = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth_6193124714125256054();
		}
	}


	[Preserve]
	public class CoherenceSyncEnemyC_75a6438d17923ed4bbf57e0d1b70a8fa : CoherenceSyncBaked
	{
		private SerializeEntityID entityId;
		private Logger logger = Log.GetLogger<CoherenceSyncEnemyC_75a6438d17923ed4bbf57e0d1b70a8fa>();

		// Cached targets for commands		
		private global::EnemyHealth EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_b6112fd5_d781_4762_a7d5_6c49ee03d9f2_CommandTarget;		
		private global::EnemySyncInit EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemySyncInit__char_46_SetReferences_59c44945_06c3_4fe7_81df_2a7111dcfc20_CommandTarget;

		private IClient client;
		private CoherenceBridge bridge;

		private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
		{
			["ba447dfb-1812-4d5e-b886-8215e6029ca7"] = new Binding_75a6438d17923ed4bbf57e0d1b70a8fa_ba447dfb_1812_4d5e_b886_8215e6029ca7(),
			["ddb74f89-d2d9-4ce0-87c5-aba73101896b"] = new Binding_75a6438d17923ed4bbf57e0d1b70a8fa_ddb74f89_d2d9_4ce0_87c5_aba73101896b(),
			["84ab2c91-ef90-4d6b-be49-7f4cb30dc3a9"] = new Binding_75a6438d17923ed4bbf57e0d1b70a8fa_84ab2c91_ef90_4d6b_be49_7f4cb30dc3a9(),
		};

		private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings =
			new Dictionary<string, Action<CommandBinding, CommandsHandler>>();

		public CoherenceSyncEnemyC_75a6438d17923ed4bbf57e0d1b70a8fa()
		{
			bakedCommandBindings.Add("b6112fd5-d781-4762-a7d5-6c49ee03d9f2", BakeCommandBinding_EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_b6112fd5_d781_4762_a7d5_6c49ee03d9f2);
			bakedCommandBindings.Add("59c44945-06c3-4fe7-81df-2a7111dcfc20", BakeCommandBinding_EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemySyncInit__char_46_SetReferences_59c44945_06c3_4fe7_81df_2a7111dcfc20);
		}

		public override Binding BakeValueBinding(Binding valueBinding)
		{
			if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
			{
				valueBinding.CloneTo(bakedBinding);
				return bakedBinding;
			}

			return null;
		}

		public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
			{
				commandBindingBaker.Invoke(commandBinding, commandsHandler);
			}
		}
		private void BakeCommandBinding_EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_b6112fd5_d781_4762_a7d5_6c49ee03d9f2(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_b6112fd5_d781_4762_a7d5_6c49ee03d9f2_CommandTarget = (global::EnemyHealth)commandBinding.UnityComponent;
			commandsHandler.AddBakedCommand("EnemyHealth.Die", "()",
				SendCommand_EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_b6112fd5_d781_4762_a7d5_6c49ee03d9f2, ReceiveLocalCommand_EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_b6112fd5_d781_4762_a7d5_6c49ee03d9f2, MessageTarget.All, EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_b6112fd5_d781_4762_a7d5_6c49ee03d9f2_CommandTarget,false);
		}
		private void BakeCommandBinding_EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemySyncInit__char_46_SetReferences_59c44945_06c3_4fe7_81df_2a7111dcfc20(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemySyncInit__char_46_SetReferences_59c44945_06c3_4fe7_81df_2a7111dcfc20_CommandTarget = (global::EnemySyncInit)commandBinding.UnityComponent;
			commandsHandler.AddBakedCommand("EnemySyncInit.SetReferences", "(System.String)",
				SendCommand_EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemySyncInit__char_46_SetReferences_59c44945_06c3_4fe7_81df_2a7111dcfc20, ReceiveLocalCommand_EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemySyncInit__char_46_SetReferences_59c44945_06c3_4fe7_81df_2a7111dcfc20, MessageTarget.All, EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemySyncInit__char_46_SetReferences_59c44945_06c3_4fe7_81df_2a7111dcfc20_CommandTarget,false);
		}

		public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName)
		{
			if (!usesLodsAtRuntime)
			{
				return null;
			}

			if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
	
			logger.Warning($"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");

			return null;
		}

		public override void Dispose()
		{
		}

		public override void Initialize(SerializeEntityID entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
		{
			this.logger = logger.With<CoherenceSyncEnemyC_75a6438d17923ed4bbf57e0d1b70a8fa>();
			this.bridge = bridge;
			this.entityId = entityId;
			this.client = client;
		}
		void SendCommand_EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_b6112fd5_d781_4762_a7d5_6c49ee03d9f2(MessageTarget target, object[] args)
		{
			var command = new EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_b6112fd5_d781_4762_a7d5_6c49ee03d9f2();
			client.SendCommand(command, target, entityId);
		}

		void ReceiveLocalCommand_EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_b6112fd5_d781_4762_a7d5_6c49ee03d9f2(MessageTarget target, object[] args)
		{
			var command = new EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_b6112fd5_d781_4762_a7d5_6c49ee03d9f2();
			ReceiveCommand_EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_b6112fd5_d781_4762_a7d5_6c49ee03d9f2(command);
		}

		void ReceiveCommand_EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_b6112fd5_d781_4762_a7d5_6c49ee03d9f2(EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_b6112fd5_d781_4762_a7d5_6c49ee03d9f2 command)
		{
			var target = EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_b6112fd5_d781_4762_a7d5_6c49ee03d9f2_CommandTarget;
			target.Die();
		}
		void SendCommand_EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemySyncInit__char_46_SetReferences_59c44945_06c3_4fe7_81df_2a7111dcfc20(MessageTarget target, object[] args)
		{
			var command = new EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemySyncInit__char_46_SetReferences_59c44945_06c3_4fe7_81df_2a7111dcfc20();
			int i = 0;
			command.enemySpawner = (string)((System.String)args[i++]);
			client.SendCommand(command, target, entityId);
		}

		void ReceiveLocalCommand_EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemySyncInit__char_46_SetReferences_59c44945_06c3_4fe7_81df_2a7111dcfc20(MessageTarget target, object[] args)
		{
			var command = new EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemySyncInit__char_46_SetReferences_59c44945_06c3_4fe7_81df_2a7111dcfc20();
			int i = 0;
			command.enemySpawner = (string)((System.String)args[i++]);
			ReceiveCommand_EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemySyncInit__char_46_SetReferences_59c44945_06c3_4fe7_81df_2a7111dcfc20(command);
		}

		void ReceiveCommand_EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemySyncInit__char_46_SetReferences_59c44945_06c3_4fe7_81df_2a7111dcfc20(EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemySyncInit__char_46_SetReferences_59c44945_06c3_4fe7_81df_2a7111dcfc20 command)
		{
			var target = EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemySyncInit__char_46_SetReferences_59c44945_06c3_4fe7_81df_2a7111dcfc20_CommandTarget;
			target.SetReferences((System.String)(command.enemySpawner));
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				case EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_b6112fd5_d781_4762_a7d5_6c49ee03d9f2 castedCommand:
					ReceiveCommand_EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_b6112fd5_d781_4762_a7d5_6c49ee03d9f2(castedCommand);
					break;
				case EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemySyncInit__char_46_SetReferences_59c44945_06c3_4fe7_81df_2a7111dcfc20 castedCommand:
					ReceiveCommand_EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemySyncInit__char_46_SetReferences_59c44945_06c3_4fe7_81df_2a7111dcfc20(castedCommand);
					break;
				default:
					logger.Warning($"[CoherenceSyncEnemyC_75a6438d17923ed4bbf57e0d1b70a8fa] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
