// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct DummyEnemy_03cae38ad2ee1be41926ecf791a4649a_EnemyHealth__char_46_Die_85487165_1b87_44c1_8050_e2e0e67bb4ff : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalDummyEnemy_03cae38ad2ee1be41926ecf791a4649a_EnemyHealth__char_46_Die_85487165_1b87_44c1_8050_e2e0e67bb4ff;

		public static void Serialize(DummyEnemy_03cae38ad2ee1be41926ecf791a4649a_EnemyHealth__char_46_Die_85487165_1b87_44c1_8050_e2e0e67bb4ff commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static DummyEnemy_03cae38ad2ee1be41926ecf791a4649a_EnemyHealth__char_46_Die_85487165_1b87_44c1_8050_e2e0e67bb4ff Deserialize(IInProtocolBitStream bitStream)
		{

			return new DummyEnemy_03cae38ad2ee1be41926ecf791a4649a_EnemyHealth__char_46_Die_85487165_1b87_44c1_8050_e2e0e67bb4ff
			(
			){};
		}
	}
}
