// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct DummyEnemy_03cae38ad2ee1be41926ecf791a4649a_EnemySyncInit__char_46_SetReferences_c90cdd83_0b27_4380_ac1d_212aec63515c : IEntityCommand
	{
		public string enemySpawner;

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalDummyEnemy_03cae38ad2ee1be41926ecf791a4649a_EnemySyncInit__char_46_SetReferences_c90cdd83_0b27_4380_ac1d_212aec63515c;

		public DummyEnemy_03cae38ad2ee1be41926ecf791a4649a_EnemySyncInit__char_46_SetReferences_c90cdd83_0b27_4380_ac1d_212aec63515c
		(
			string dataenemySpawner
		)
		{
			enemySpawner = dataenemySpawner;
		}

		public static void Serialize(DummyEnemy_03cae38ad2ee1be41926ecf791a4649a_EnemySyncInit__char_46_SetReferences_c90cdd83_0b27_4380_ac1d_212aec63515c commandData, IOutProtocolBitStream bitStream)
		{
			bitStream.WriteShortString(commandData.enemySpawner);
		}

		public static DummyEnemy_03cae38ad2ee1be41926ecf791a4649a_EnemySyncInit__char_46_SetReferences_c90cdd83_0b27_4380_ac1d_212aec63515c Deserialize(IInProtocolBitStream bitStream)
		{
			var dataenemySpawner = bitStream.ReadShortString();

			return new DummyEnemy_03cae38ad2ee1be41926ecf791a4649a_EnemySyncInit__char_46_SetReferences_c90cdd83_0b27_4380_ac1d_212aec63515c
			(
				dataenemySpawner
			){};
		}
	}
}
