// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct DummyEnemyMoving_d6864f6b08ef2f74cb5656579a40e8c1_EnemySyncInit__char_46_SetReferences_036db983_680a_4f7e_a234_076b1e65a181 : IEntityCommand
	{
		public string enemySpawner;

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalDummyEnemyMoving_d6864f6b08ef2f74cb5656579a40e8c1_EnemySyncInit__char_46_SetReferences_036db983_680a_4f7e_a234_076b1e65a181;

		public DummyEnemyMoving_d6864f6b08ef2f74cb5656579a40e8c1_EnemySyncInit__char_46_SetReferences_036db983_680a_4f7e_a234_076b1e65a181
		(
			string dataenemySpawner
		)
		{
			enemySpawner = dataenemySpawner;
		}

		public static void Serialize(DummyEnemyMoving_d6864f6b08ef2f74cb5656579a40e8c1_EnemySyncInit__char_46_SetReferences_036db983_680a_4f7e_a234_076b1e65a181 commandData, IOutProtocolBitStream bitStream)
		{
			bitStream.WriteShortString(commandData.enemySpawner);
		}

		public static DummyEnemyMoving_d6864f6b08ef2f74cb5656579a40e8c1_EnemySyncInit__char_46_SetReferences_036db983_680a_4f7e_a234_076b1e65a181 Deserialize(IInProtocolBitStream bitStream)
		{
			var dataenemySpawner = bitStream.ReadShortString();

			return new DummyEnemyMoving_d6864f6b08ef2f74cb5656579a40e8c1_EnemySyncInit__char_46_SetReferences_036db983_680a_4f7e_a234_076b1e65a181
			(
				dataenemySpawner
			){};
		}
	}
}
