// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct DummyEnemyMoving_d6864f6b08ef2f74cb5656579a40e8c1_EnemyHealth__char_46_Die_c2f56aad_9046_4e74_bad1_fb853ce070d4 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalDummyEnemyMoving_d6864f6b08ef2f74cb5656579a40e8c1_EnemyHealth__char_46_Die_c2f56aad_9046_4e74_bad1_fb853ce070d4;

		public static void Serialize(DummyEnemyMoving_d6864f6b08ef2f74cb5656579a40e8c1_EnemyHealth__char_46_Die_c2f56aad_9046_4e74_bad1_fb853ce070d4 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static DummyEnemyMoving_d6864f6b08ef2f74cb5656579a40e8c1_EnemyHealth__char_46_Die_c2f56aad_9046_4e74_bad1_fb853ce070d4 Deserialize(IInProtocolBitStream bitStream)
		{

			return new DummyEnemyMoving_d6864f6b08ef2f74cb5656579a40e8c1_EnemyHealth__char_46_Die_c2f56aad_9046_4e74_bad1_fb853ce070d4
			(
			){};
		}
	}
}
