// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct DummyEnemy_03cae38ad2ee1be41926ecf791a4649a_EnemyHealth__char_46_Die_c27ce6a5_8b12_47d2_aad4_a576db18fc49 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalDummyEnemy_03cae38ad2ee1be41926ecf791a4649a_EnemyHealth__char_46_Die_c27ce6a5_8b12_47d2_aad4_a576db18fc49;

		public static void Serialize(DummyEnemy_03cae38ad2ee1be41926ecf791a4649a_EnemyHealth__char_46_Die_c27ce6a5_8b12_47d2_aad4_a576db18fc49 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static DummyEnemy_03cae38ad2ee1be41926ecf791a4649a_EnemyHealth__char_46_Die_c27ce6a5_8b12_47d2_aad4_a576db18fc49 Deserialize(IInProtocolBitStream bitStream)
		{

			return new DummyEnemy_03cae38ad2ee1be41926ecf791a4649a_EnemyHealth__char_46_Die_c27ce6a5_8b12_47d2_aad4_a576db18fc49
			(
			){};
		}
	}
}
