// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct EnemyD_bced0933a9712ac4aac05cdf91d8f3f8_EnemyHealth__char_46_Die_ca26e76b_08eb_4f71_92fd_52e510b0aade : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalEnemyD_bced0933a9712ac4aac05cdf91d8f3f8_EnemyHealth__char_46_Die_ca26e76b_08eb_4f71_92fd_52e510b0aade;

		public static void Serialize(EnemyD_bced0933a9712ac4aac05cdf91d8f3f8_EnemyHealth__char_46_Die_ca26e76b_08eb_4f71_92fd_52e510b0aade commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static EnemyD_bced0933a9712ac4aac05cdf91d8f3f8_EnemyHealth__char_46_Die_ca26e76b_08eb_4f71_92fd_52e510b0aade Deserialize(IInProtocolBitStream bitStream)
		{

			return new EnemyD_bced0933a9712ac4aac05cdf91d8f3f8_EnemyHealth__char_46_Die_ca26e76b_08eb_4f71_92fd_52e510b0aade
			(
			){};
		}
	}
}
