// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Enemy_7365a46dbef03be41b6173e6147d68d1_EnemySyncInit__char_46_SetReferences_88fa8c05_3997_4a41_aedd_c5155114f209 : IEntityCommand
	{
		public SerializeEntityID enemySpawner;

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalEnemy_7365a46dbef03be41b6173e6147d68d1_EnemySyncInit__char_46_SetReferences_88fa8c05_3997_4a41_aedd_c5155114f209;

		public Enemy_7365a46dbef03be41b6173e6147d68d1_EnemySyncInit__char_46_SetReferences_88fa8c05_3997_4a41_aedd_c5155114f209
		(
			SerializeEntityID dataenemySpawner
		)
		{
			enemySpawner = dataenemySpawner;
		}

		public static void Serialize(Enemy_7365a46dbef03be41b6173e6147d68d1_EnemySyncInit__char_46_SetReferences_88fa8c05_3997_4a41_aedd_c5155114f209 commandData, IOutProtocolBitStream bitStream)
		{
			bitStream.WriteEntity(commandData.enemySpawner);
		}

		public static Enemy_7365a46dbef03be41b6173e6147d68d1_EnemySyncInit__char_46_SetReferences_88fa8c05_3997_4a41_aedd_c5155114f209 Deserialize(IInProtocolBitStream bitStream)
		{
			var dataenemySpawner = bitStream.ReadEntity();

			return new Enemy_7365a46dbef03be41b6173e6147d68d1_EnemySyncInit__char_46_SetReferences_88fa8c05_3997_4a41_aedd_c5155114f209
			(
				dataenemySpawner
			){};
		}
	}
}
