// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemyHealth__char_46_Die_fbbba866_44ca_4742_bbe4_4f475d052f97 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalEnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemyHealth__char_46_Die_fbbba866_44ca_4742_bbe4_4f475d052f97;

		public static void Serialize(EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemyHealth__char_46_Die_fbbba866_44ca_4742_bbe4_4f475d052f97 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemyHealth__char_46_Die_fbbba866_44ca_4742_bbe4_4f475d052f97 Deserialize(IInProtocolBitStream bitStream)
		{

			return new EnemyA_fb33efce218f91746a8e1743d2d6c0f9_EnemyHealth__char_46_Die_fbbba866_44ca_4742_bbe4_4f475d052f97
			(
			){};
		}
	}
}
