// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemySyncInit__char_46_SetReferences_a36f68fc_d2ff_407e_b1bb_7a6268791147 : IEntityCommand
	{
		public string enemySpawner;

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalEnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemySyncInit__char_46_SetReferences_a36f68fc_d2ff_407e_b1bb_7a6268791147;

		public EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemySyncInit__char_46_SetReferences_a36f68fc_d2ff_407e_b1bb_7a6268791147
		(
			string dataenemySpawner
		)
		{
			enemySpawner = dataenemySpawner;
		}

		public static void Serialize(EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemySyncInit__char_46_SetReferences_a36f68fc_d2ff_407e_b1bb_7a6268791147 commandData, IOutProtocolBitStream bitStream)
		{
			bitStream.WriteShortString(commandData.enemySpawner);
		}

		public static EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemySyncInit__char_46_SetReferences_a36f68fc_d2ff_407e_b1bb_7a6268791147 Deserialize(IInProtocolBitStream bitStream)
		{
			var dataenemySpawner = bitStream.ReadShortString();

			return new EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemySyncInit__char_46_SetReferences_a36f68fc_d2ff_407e_b1bb_7a6268791147
			(
				dataenemySpawner
			){};
		}
	}
}
