// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct EnemyD_bced0933a9712ac4aac05cdf91d8f3f8_EnemyHealth__char_46_Die_3a5a326d_af4d_4f44_8a60_3a7d10a95ab5 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalEnemyD_bced0933a9712ac4aac05cdf91d8f3f8_EnemyHealth__char_46_Die_3a5a326d_af4d_4f44_8a60_3a7d10a95ab5;

		public static void Serialize(EnemyD_bced0933a9712ac4aac05cdf91d8f3f8_EnemyHealth__char_46_Die_3a5a326d_af4d_4f44_8a60_3a7d10a95ab5 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static EnemyD_bced0933a9712ac4aac05cdf91d8f3f8_EnemyHealth__char_46_Die_3a5a326d_af4d_4f44_8a60_3a7d10a95ab5 Deserialize(IInProtocolBitStream bitStream)
		{

			return new EnemyD_bced0933a9712ac4aac05cdf91d8f3f8_EnemyHealth__char_46_Die_3a5a326d_af4d_4f44_8a60_3a7d10a95ab5
			(
			){};
		}
	}
}
