// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_26acf062_bd11_4865_a66b_bf066eeeeec1 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalEnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_26acf062_bd11_4865_a66b_bf066eeeeec1;

		public static void Serialize(EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_26acf062_bd11_4865_a66b_bf066eeeeec1 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_26acf062_bd11_4865_a66b_bf066eeeeec1 Deserialize(IInProtocolBitStream bitStream)
		{

			return new EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_26acf062_bd11_4865_a66b_bf066eeeeec1
			(
			){};
		}
	}
}
