// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct Enemy_7365a46dbef03be41b6173e6147d68d1_UnityEngine__char_46_Animator_3583843158289549039 : ICoherenceComponentData
	{
		public bool Walking;
		public float Angle;

		public override string ToString()
		{
			return $"Enemy_7365a46dbef03be41b6173e6147d68d1_UnityEngine__char_46_Animator_3583843158289549039(Walking: {Walking}, Angle: {Angle})";
		}

		public uint GetComponentType() => Definition.InternalEnemy_7365a46dbef03be41b6173e6147d68d1_UnityEngine__char_46_Animator_3583843158289549039;

		public const int order = 0;

		public uint FieldsMask => 0b00000000000000000000000000000011;

		public int GetComponentOrder() => order;
		public bool IsSendOrdered() { return false; }

		public AbsoluteSimulationFrame Frame;
	

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (Enemy_7365a46dbef03be41b6173e6147d68d1_UnityEngine__char_46_Animator_3583843158289549039)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				Walking = other.Walking;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				Angle = other.Angle;
			}
			mask >>= 1;
			return this;
		}

		public uint DiffWith(ICoherenceComponentData data)
		{
			throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");

		}

		public static uint Serialize(Enemy_7365a46dbef03be41b6173e6147d68d1_UnityEngine__char_46_Animator_3583843158289549039 data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				var fieldValue = data.Walking;

				bitStream.WriteBool(fieldValue);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				var fieldValue = data.Angle;

				bitStream.WriteFloat(fieldValue, FloatMeta.NoCompression());
			}
			mask >>= 1;

			return mask;
		}

		public static (Enemy_7365a46dbef03be41b6173e6147d68d1_UnityEngine__char_46_Animator_3583843158289549039, uint) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Enemy_7365a46dbef03be41b6173e6147d68d1_UnityEngine__char_46_Animator_3583843158289549039();
	
			if (bitStream.ReadMask())
			{
				val.Walking = bitStream.ReadBool();
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.Angle = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000010;
			}
			return (val, mask);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as Enemy_7365a46dbef03be41b6173e6147d68d1_UnityEngine__char_46_Animator_3583843158289549039?;
	
		}
	}
}