// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_7d5aa261_3832_45b3_8e0b_000a6ba68241 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalEnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_7d5aa261_3832_45b3_8e0b_000a6ba68241;

		public static void Serialize(EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_7d5aa261_3832_45b3_8e0b_000a6ba68241 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_7d5aa261_3832_45b3_8e0b_000a6ba68241 Deserialize(IInProtocolBitStream bitStream)
		{

			return new EnemyB_5714c7c58551c2843bebf23f9feebbe2_EnemyHealth__char_46_Die_7d5aa261_3832_45b3_8e0b_000a6ba68241
			(
			){};
		}
	}
}
