// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_d091bb8f_a40a_431f_9707_34d83e354c07 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalEnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_d091bb8f_a40a_431f_9707_34d83e354c07;

		public static void Serialize(EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_d091bb8f_a40a_431f_9707_34d83e354c07 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_d091bb8f_a40a_431f_9707_34d83e354c07 Deserialize(IInProtocolBitStream bitStream)
		{

			return new EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_d091bb8f_a40a_431f_9707_34d83e354c07
			(
			){};
		}
	}
}
