// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_b6112fd5_d781_4762_a7d5_6c49ee03d9f2 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalEnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_b6112fd5_d781_4762_a7d5_6c49ee03d9f2;

		public static void Serialize(EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_b6112fd5_d781_4762_a7d5_6c49ee03d9f2 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_b6112fd5_d781_4762_a7d5_6c49ee03d9f2 Deserialize(IInProtocolBitStream bitStream)
		{

			return new EnemyC_75a6438d17923ed4bbf57e0d1b70a8fa_EnemyHealth__char_46_Die_b6112fd5_d781_4762_a7d5_6c49ee03d9f2
			(
			){};
		}
	}
}
