// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct EnemyD_bced0933a9712ac4aac05cdf91d8f3f8_EnemySyncInit__char_46_SetReferences_722794ab_8faa_4e48_b5da_23968464a290 : IEntityCommand
	{
		public string enemySpawner;

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalEnemyD_bced0933a9712ac4aac05cdf91d8f3f8_EnemySyncInit__char_46_SetReferences_722794ab_8faa_4e48_b5da_23968464a290;

		public EnemyD_bced0933a9712ac4aac05cdf91d8f3f8_EnemySyncInit__char_46_SetReferences_722794ab_8faa_4e48_b5da_23968464a290
		(
			string dataenemySpawner
		)
		{
			enemySpawner = dataenemySpawner;
		}

		public static void Serialize(EnemyD_bced0933a9712ac4aac05cdf91d8f3f8_EnemySyncInit__char_46_SetReferences_722794ab_8faa_4e48_b5da_23968464a290 commandData, IOutProtocolBitStream bitStream)
		{
			bitStream.WriteShortString(commandData.enemySpawner);
		}

		public static EnemyD_bced0933a9712ac4aac05cdf91d8f3f8_EnemySyncInit__char_46_SetReferences_722794ab_8faa_4e48_b5da_23968464a290 Deserialize(IInProtocolBitStream bitStream)
		{
			var dataenemySpawner = bitStream.ReadShortString();

			return new EnemyD_bced0933a9712ac4aac05cdf91d8f3f8_EnemySyncInit__char_46_SetReferences_722794ab_8faa_4e48_b5da_23968464a290
			(
				dataenemySpawner
			){};
		}
	}
}
