// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Player_9b83865ad432b2840a2ba6c6e5d0fada_IceSpikesTestSpell__char_46_CastSpikes_9e7896fc_a8a5_4139_991e_5a6a7a91c14d : IEntityCommand
	{
		public bool demonic;

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalPlayer_9b83865ad432b2840a2ba6c6e5d0fada_IceSpikesTestSpell__char_46_CastSpikes_9e7896fc_a8a5_4139_991e_5a6a7a91c14d;

		public Player_9b83865ad432b2840a2ba6c6e5d0fada_IceSpikesTestSpell__char_46_CastSpikes_9e7896fc_a8a5_4139_991e_5a6a7a91c14d
		(
			bool datademonic
		)
		{
			demonic = datademonic;
		}

		public static void Serialize(Player_9b83865ad432b2840a2ba6c6e5d0fada_IceSpikesTestSpell__char_46_CastSpikes_9e7896fc_a8a5_4139_991e_5a6a7a91c14d commandData, IOutProtocolBitStream bitStream)
		{
			bitStream.WriteBool(commandData.demonic);
		}

		public static Player_9b83865ad432b2840a2ba6c6e5d0fada_IceSpikesTestSpell__char_46_CastSpikes_9e7896fc_a8a5_4139_991e_5a6a7a91c14d Deserialize(IInProtocolBitStream bitStream)
		{
			var datademonic = bitStream.ReadBool();

			return new Player_9b83865ad432b2840a2ba6c6e5d0fada_IceSpikesTestSpell__char_46_CastSpikes_9e7896fc_a8a5_4139_991e_5a6a7a91c14d
			(
				datademonic
			){};
		}
	}
}
