// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Player_9b83865ad432b2840a2ba6c6e5d0fada_AbilityInputSystem__char_46_AttemptCast_1671ea92_37c2_4f0f_898a_da265628b53a : IEntityCommand
	{
		public int tier;

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalPlayer_9b83865ad432b2840a2ba6c6e5d0fada_AbilityInputSystem__char_46_AttemptCast_1671ea92_37c2_4f0f_898a_da265628b53a;

		public Player_9b83865ad432b2840a2ba6c6e5d0fada_AbilityInputSystem__char_46_AttemptCast_1671ea92_37c2_4f0f_898a_da265628b53a
		(
			int datatier
		)
		{
			tier = datatier;
		}

		public static void Serialize(Player_9b83865ad432b2840a2ba6c6e5d0fada_AbilityInputSystem__char_46_AttemptCast_1671ea92_37c2_4f0f_898a_da265628b53a commandData, IOutProtocolBitStream bitStream)
		{
			bitStream.WriteIntegerRange(commandData.tier, 32, -2147483648);
		}

		public static Player_9b83865ad432b2840a2ba6c6e5d0fada_AbilityInputSystem__char_46_AttemptCast_1671ea92_37c2_4f0f_898a_da265628b53a Deserialize(IInProtocolBitStream bitStream)
		{
			var datatier = bitStream.ReadIntegerRange(32, -2147483648);

			return new Player_9b83865ad432b2840a2ba6c6e5d0fada_AbilityInputSystem__char_46_AttemptCast_1671ea92_37c2_4f0f_898a_da265628b53a
			(
				datatier
			){};
		}
	}
}
