// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Player_9b83865ad432b2840a2ba6c6e5d0fada_PlayerHealth__char_46_PlayerDown_b8a2cb78_fa6d_4815_9c83_f022908165ad : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalPlayer_9b83865ad432b2840a2ba6c6e5d0fada_PlayerHealth__char_46_PlayerDown_b8a2cb78_fa6d_4815_9c83_f022908165ad;

		public static void Serialize(Player_9b83865ad432b2840a2ba6c6e5d0fada_PlayerHealth__char_46_PlayerDown_b8a2cb78_fa6d_4815_9c83_f022908165ad commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Player_9b83865ad432b2840a2ba6c6e5d0fada_PlayerHealth__char_46_PlayerDown_b8a2cb78_fa6d_4815_9c83_f022908165ad Deserialize(IInProtocolBitStream bitStream)
		{

			return new Player_9b83865ad432b2840a2ba6c6e5d0fada_PlayerHealth__char_46_PlayerDown_b8a2cb78_fa6d_4815_9c83_f022908165ad
			(
			){};
		}
	}
}
