// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Player_9b83865ad432b2840a2ba6c6e5d0fada_PlayerSpellIceDash__char_46_DashFinished_d3a90726_4da1_433b_931d_52597d0bf64b : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalPlayer_9b83865ad432b2840a2ba6c6e5d0fada_PlayerSpellIceDash__char_46_DashFinished_d3a90726_4da1_433b_931d_52597d0bf64b;

		public static void Serialize(Player_9b83865ad432b2840a2ba6c6e5d0fada_PlayerSpellIceDash__char_46_DashFinished_d3a90726_4da1_433b_931d_52597d0bf64b commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Player_9b83865ad432b2840a2ba6c6e5d0fada_PlayerSpellIceDash__char_46_DashFinished_d3a90726_4da1_433b_931d_52597d0bf64b Deserialize(IInProtocolBitStream bitStream)
		{

			return new Player_9b83865ad432b2840a2ba6c6e5d0fada_PlayerSpellIceDash__char_46_DashFinished_d3a90726_4da1_433b_931d_52597d0bf64b
			(
			){};
		}
	}
}
