// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Player_9b83865ad432b2840a2ba6c6e5d0fada_PlayerHealth__char_46_PlayerDown_2a25c6f4_c7a6_4a16_a1e4_c53af30c4963 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalPlayer_9b83865ad432b2840a2ba6c6e5d0fada_PlayerHealth__char_46_PlayerDown_2a25c6f4_c7a6_4a16_a1e4_c53af30c4963;

		public static void Serialize(Player_9b83865ad432b2840a2ba6c6e5d0fada_PlayerHealth__char_46_PlayerDown_2a25c6f4_c7a6_4a16_a1e4_c53af30c4963 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Player_9b83865ad432b2840a2ba6c6e5d0fada_PlayerHealth__char_46_PlayerDown_2a25c6f4_c7a6_4a16_a1e4_c53af30c4963 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Player_9b83865ad432b2840a2ba6c6e5d0fada_PlayerHealth__char_46_PlayerDown_2a25c6f4_c7a6_4a16_a1e4_c53af30c4963
			(
			){};
		}
	}
}
