// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_fa79d985_aa4b_4352_9ecf_918c5ebf41c4 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalTurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_fa79d985_aa4b_4352_9ecf_918c5ebf41c4;

		public static void Serialize(TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_fa79d985_aa4b_4352_9ecf_918c5ebf41c4 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_fa79d985_aa4b_4352_9ecf_918c5ebf41c4 Deserialize(IInProtocolBitStream bitStream)
		{

			return new TurretEnemy_05434230e22f555459cd21106aeb67e2_EnemyHealth__char_46_Die_fa79d985_aa4b_4352_9ecf_918c5ebf41c4
			(
			){};
		}
	}
}
